version: '3'

services:
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /home/ubuntu/.forever/:/var/log/forever/
    links:
      - loki
    command: -config.file=/etc/promtail/promtail-config.yaml

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
